# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l0araC <- function(x, y, family, lam, nonneg, maxit, eps) {
    .Call(`_l0ara_l0araC`, x, y, family, lam, nonneg, maxit, eps)
}

#' @export
solve_dense_lsconjgrad <- function(input) {
    .Call(`_l0ara_solve_dense_lsconjgrad`, input)
}

#' @export
solve_sparse_LDLT <- function(input) {
    .Call(`_l0ara_solve_sparse_LDLT`, input)
}

#' @export
solve_sparse_lsconjgrad <- function(input) {
    .Call(`_l0ara_solve_sparse_lsconjgrad`, input)
}

wls_solve <- function(X, y, w) {
    .Call(`_l0ara_wls_solve`, X, y, w)
}

